workflows:
  ios-development:
    name: QuoteWidget iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_PROJECT: "QuoteWidget.xcodeproj"
        XCODE_SCHEME: "QuoteWidget"

    scripts:
      - name: Build IPA
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath derived_data \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Package IPA
        script: |
          mkdir -p Payload
          cp -r derived_data/Build/Products/Debug-iphoneos/QuoteWidget.app Payload/
          zip -r QuoteWidget.ipa Payload
          rm -rf Payload

    artifacts:
      - "*.ipa"

    publishing:
      email:
        recipients:
          - neutralnie7@gmail.com
        notify:
          success: true
          failure: true
